apiVersion: broker.amq.io/v2alpha2
kind: ActiveMQArtemis
metadata:
 name: ex-aao
spec:
 deploymentPlan:
   size: 2
   image: registry.redhat.io/amq7/amq-broker:7.6
 adminUser: admin
 adminPassword: admin
 console:
   expose: true
   sslEnabled: true
   sslSecret: ex-aao-amqp-secret
   useClientAuth: true
 acceptors:
 - name: amqp
   protocols: amqp
   port: 5672
   sslEnabled: true
   needClientAuth: false
   wantClientAuth: false
   expose: true
